export const DUMMY_QUESTIONS_LIST = [
  {
    id: 1,
    question: "Soal dummy 1",
    answers: [
      { option: "A", text: "Jawaban 1A" },
      { option: "B", text: "Jawaban 1B" },
      { option: "C", text: "Jawaban 1C" },
      { option: "D", text: "Jawaban 1D" },
      { option: "E", text: "Jawaban 1E" },
    ],
    correctAnswer: "A",
  },
  {
    id: 2,
    question: "Soal dummy 2",
    answers: [
      { option: "A", text: "Jawaban 2A" },
      { option: "B", text: "Jawaban 2B" },
      { option: "C", text: "Jawaban 2C" },
      { option: "D", text: "Jawaban 2D" },
      { option: "E", text: "Jawaban 2E" },
    ],
    correctAnswer: "B",
  },
  {
    id: 3,
    question: "Soal dummy 3",
    answers: [
      { option: "A", text: "Jawaban 3A" },
      { option: "B", text: "Jawaban 3B" },
      { option: "C", text: "Jawaban 3C" },
      { option: "D", text: "Jawaban 3D" },
      { option: "E", text: "Jawaban 3E" },
    ],
    correctAnswer: "C",
  },
  {
    id: 4,
    question: "Soal dummy 4",
    answers: [
      { option: "A", text: "Jawaban 4A" },
      { option: "B", text: "Jawaban 4B" },
      { option: "C", text: "Jawaban 4C" },
      { option: "D", text: "Jawaban 4D" },
      { option: "E", text: "Jawaban 4E" },
    ],
    correctAnswer: "D",
  },
  {
    id: 5,
    question: "Soal dummy 5",
    answers: [
      { option: "A", text: "Jawaban 5A" },
      { option: "B", text: "Jawaban 5B" },
      { option: "C", text: "Jawaban 5C" },
      { option: "D", text: "Jawaban 5D" },
      { option: "E", text: "Jawaban 5E" },
    ],
    correctAnswer: "E",
  },
  {
    id: 6,
    question: "Soal dummy 6",
    answers: [
      { option: "A", text: "Jawaban 6A" },
      { option: "B", text: "Jawaban 6B" },
      { option: "C", text: "Jawaban 6C" },
      { option: "D", text: "Jawaban 6D" },
      { option: "E", text: "Jawaban 6E" },
    ],
    correctAnswer: "A",
  },
  {
    id: 7,
    question: "Soal dummy 7",
    answers: [
      { option: "A", text: "Jawaban 7A" },
      { option: "B", text: "Jawaban 7B" },
      { option: "C", text: "Jawaban 7C" },
      { option: "D", text: "Jawaban 7D" },
      { option: "E", text: "Jawaban 7E" },
    ],
    correctAnswer: "B",
  },
  {
    id: 8,
    question: "Soal dummy 8",
    answers: [
      { option: "A", text: "Jawaban 8A" },
      { option: "B", text: "Jawaban 8B" },
      { option: "C", text: "Jawaban 8C" },
      { option: "D", text: "Jawaban 8D" },
      { option: "E", text: "Jawaban 8E" },
    ],
    correctAnswer: "C",
  },
  {
    id: 9,
    question: "Soal dummy 9",
    answers: [
      { option: "A", text: "Jawaban 9A" },
      { option: "B", text: "Jawaban 9B" },
      { option: "C", text: "Jawaban 9C" },
      { option: "D", text: "Jawaban 9D" },
      { option: "E", text: "Jawaban 9E" },
    ],
    correctAnswer: "D",
  },
  {
    id: 10,
    question: "Soal dummy 10",
    answers: [
      { option: "A", text: "Jawaban 10A" },
      { option: "B", text: "Jawaban 10B" },
      { option: "C", text: "Jawaban 10C" },
      { option: "D", text: "Jawaban 10D" },
      { option: "E", text: "Jawaban 10E" },
    ],
    correctAnswer: "E",
  },
];
